### PR TITLE
updated plist format, added license

### PR DESCRIPTION
**Pull request by yamanote1138**
was looking over the new rachio plugin noticed several new conventions, updating this plugin to follow suit:
- updated the plist format and values where applicable
- changed `CFBundleIdentifier` to match open source pattern
- bumped version to `1.2.0` (although changing the bundle id might warrant a major version bump)
- added MIT license, but I have no strong opinion if anyone would prefer another

tested on my home installation, no issues thus far. had to delete and re-add any pushover actions since the bundle id changed, but alas...

### CODE REVIEW

**Comment by indigodomo** [comment]
A few comments: the bundle ID doesn't really need to change (and therefore cause everyone to recreate their actions) unless you don't want to leave it as it is now. We've decided the GitHub stuff isn't (yet) needed, at least in the Info.plist. So, basically, unless you really want the changes made, I don't really see the need.

**Comment by indigodomo** [comment]
The license though is good...

**Comment by yamanote1138** [comment]
I have no objections to leaving my old info in the bundle.  for the record, feel free to change it to whatever you'd like at a later date :)

I'll pull any breaking changes out and resubmit

**Comment by yamanote1138** [comment]
done. removed bundle id change and demoted version bump to a patch

**Pull request merged**
